### ISSUE TITLE
Implement automatic language resolution

### ISSUE THREAD

**Issue by reaganmcf** [reaganmcf/lightmon#6]
Just running `lightmon` should try to automatically determine what the watch patterns and exec commands should be used. This is fairly trivial for configurations such as `rust` and `node`, but will almost be impossible for languages like `c` and `c++`

**Comment by reaganmcf** [comment]
@alayshahh Keep in mind that #2 and #3 are kind of related here. If there is a config file (how this is to be implemented has not been finalized), `lightmon` should prioritize a config file (if present) over the automatic language resolution method

**Comment by alayshahh** [comment]
> @alayshahh Keep in mind that #2 and #3 are kind of related here. If there is a config file (how this is to be implemented has not been finalized), `lightmon` should prioritize a config file (if present) over the automatic language resolution method

gotcha, ill make it so we can easily add the feature.
