### ISSUE TITLE
For shell mode: Ensure that path to shell script actually exists.

### ISSUE THREAD

**Issue by alayshahh** [reaganmcf/lightmon#9]
Make sure no bad args passed

**Comment by alayshahh** [comment]
@reaganmcf this would get rid of the ability to pass in a script directly, do we still want to do something like this?
i.e. this would be invalid
`lightmon shell -s python main.py -w .py`
users would have to put this command in a `.sh` file

**Comment by reaganmcf** [comment]
> @reaganmcf this would get rid of the ability to pass in a script directly, do we still want to do something like this?
> 
> i.e. this would be invalid
> 
> `lightmon shell -s python main.py -w .py`
> 
> users would have to put this command in a `.sh` file

They should not be able to pass in something that is not a shell script for shell mode, so your example is supposed to be invalid anyway.
